"""Format test cases as pytest Python code."""

from .models import CaseSpec, CaseType, FileSpec


def _snake_case(s: str) -> str:
    """Convert a string to snake_case."""
    return s.lower().replace(" ", "_").replace("-", "_")


def _format_docstring(
    description: str,
    guards: list[str] | None = None,
    effects: list[str] | None = None,
    formal: str | None = None,
    indent_level: int = 2,
) -> str:
    """Format a docstring with optional guards/effects."""
    lines = [f'"""', description]

    if guards:
        lines.append("")
        lines.append("Guards:")
        for guard in guards:
            lines.append(f"  - {guard}")

    if effects:
        lines.append("")
        lines.append("Effects:")
        for effect in effects:
            lines.append(f"  - {effect}")

    if formal:
        lines.append("")
        lines.append(f"Formal: {formal}")

    lines.append('"""')

    indent = " " * (indent_level * 4)
    return "\n".join(indent + line if line else "" for line in lines)


def _format_fixture(entity_name: str, state_name: str, is_initial: bool = False) -> str:
    """Format a pytest fixture for an entity in a given state."""
    snake_entity = _snake_case(entity_name)
    snake_state = _snake_case(state_name)

    initial_note = " (initial)" if is_initial else ""
    return f'''@pytest.fixture
def {snake_entity}_in_{snake_state}_state():
    """Create {entity_name} in {state_name}{initial_note} state."""
    # TODO: Implement fixture
    pass
'''


def _format_positive_transition_test(tc: CaseSpec) -> str:
    """Format a positive transition test."""
    snake_entity = _snake_case(tc.entity)
    snake_from = _snake_case(tc.from_state) if tc.from_state else ""

    docstring = _format_docstring(
        tc.description, guards=tc.guards, effects=tc.effects
    )

    trigger_comment = f"# Trigger: {tc.trigger}" if tc.trigger else "# TODO: Trigger transition"

    return f'''    def {tc.name}(self, {snake_entity}_in_{snake_from}_state):
{docstring}
        {trigger_comment}
        # TODO: Assert state == '{tc.to_state}'
        pass
'''


def _format_negative_transition_test(tc: CaseSpec) -> str:
    """Format a negative transition test."""
    snake_entity = _snake_case(tc.entity)
    snake_from = _snake_case(tc.from_state) if tc.from_state else ""

    return f'''    def {tc.name}(self, {snake_entity}_in_{snake_from}_state):
        """{tc.description}"""
        # TODO: Attempt invalid transition and assert it fails
        pass
'''


def _format_happy_path_test(tc: CaseSpec) -> str:
    """Format a happy path test."""
    path_str = " → ".join(tc.path) if tc.path else ""

    return f'''    def {tc.name}(self):
        """Test path: {path_str}"""
        # TODO: Walk through transitions:
        # {" -> ".join(tc.path) if tc.path else ""}
        pass
'''


def _format_invariant_test(tc: CaseSpec) -> str:
    """Format an invariant test."""
    docstring = _format_docstring(tc.description, formal=tc.formal)

    return f'''    def {tc.name}(self):
{docstring}
        # TODO: Assert invariant holds
        pass
'''


def format_test_file(test_file: FileSpec) -> str:
    """Format a complete test file as valid Python.

    Args:
        test_file: The TestFile to format.

    Returns:
        Valid Python code as a string.
    """
    lines = []

    # File docstring
    lines.append(f'"""Generated tests for {test_file.entity} entity.')
    lines.append("")
    lines.append("Auto-generated by Lattice. Regenerate with:")
    lines.append("  intent generate-tests model.yaml")
    lines.append('"""')
    lines.append("")
    lines.append("import pytest")
    lines.append("")
    lines.append("")

    # Collect unique states for fixtures
    states_needed: set[tuple[str, str]] = set()
    for tc in test_file.test_cases:
        if tc.from_state and tc.test_type in (
            CaseType.POSITIVE_TRANSITION,
            CaseType.NEGATIVE_TRANSITION,
        ):
            states_needed.add((tc.entity, tc.from_state))

    # Generate fixtures
    for entity_name, state_name in sorted(states_needed):
        lines.append(_format_fixture(entity_name, state_name))
        lines.append("")

    # Group tests by type
    positive_tests = [
        tc for tc in test_file.test_cases
        if tc.test_type == CaseType.POSITIVE_TRANSITION
    ]
    negative_tests = [
        tc for tc in test_file.test_cases
        if tc.test_type == CaseType.NEGATIVE_TRANSITION
    ]
    happy_path_tests = [
        tc for tc in test_file.test_cases
        if tc.test_type == CaseType.HAPPY_PATH
    ]
    invariant_tests = [
        tc for tc in test_file.test_cases
        if tc.test_type in (CaseType.ENTITY_INVARIANT, CaseType.SYSTEM_INVARIANT)
    ]

    # TestPositiveTransitions class
    if positive_tests:
        lines.append("class TestPositiveTransitions:")
        lines.append('    """Tests for valid state transitions."""')
        lines.append("")
        for tc in positive_tests:
            lines.append(_format_positive_transition_test(tc))

    # TestNegativeTransitions class
    if negative_tests:
        lines.append("")
        lines.append("class TestNegativeTransitions:")
        lines.append('    """Tests for invalid state transitions that should be blocked."""')
        lines.append("")
        for tc in negative_tests:
            lines.append(_format_negative_transition_test(tc))

    # TestHappyPaths class
    if happy_path_tests:
        lines.append("")
        lines.append("class TestHappyPaths:")
        lines.append('    """Tests for complete paths from initial to terminal states."""')
        lines.append("")
        for tc in happy_path_tests:
            lines.append(_format_happy_path_test(tc))

    # TestInvariants class
    if invariant_tests:
        lines.append("")
        lines.append("class TestInvariants:")
        lines.append('    """Tests for invariants that must always hold."""')
        lines.append("")
        for tc in invariant_tests:
            lines.append(_format_invariant_test(tc))

    return "\n".join(lines)


def format_system_invariants_file(test_cases: list[CaseSpec]) -> str:
    """Format a test file for system-level invariants.

    Args:
        test_cases: List of system invariant test cases.

    Returns:
        Valid Python code as a string.
    """
    lines = []

    # File docstring
    lines.append('"""Generated tests for system invariants.')
    lines.append("")
    lines.append("Auto-generated by Lattice. Regenerate with:")
    lines.append("  intent generate-tests model.yaml")
    lines.append('"""')
    lines.append("")
    lines.append("import pytest")
    lines.append("")
    lines.append("")
    lines.append("class TestSystemInvariants:")
    lines.append('    """Tests for system-wide invariants."""')
    lines.append("")

    for tc in test_cases:
        lines.append(_format_invariant_test(tc))

    return "\n".join(lines)
