"""Tests for test_generator.formatter."""

import pytest

from lattice.test_generator.formatter import (
    format_system_invariants_file,
    format_test_file,
)
from lattice.test_generator.models import TestCase, TestFile, TestType


@pytest.fixture
def positive_transition_test():
    """A positive transition test case."""
    return TestCase(
        name="test_order_draft_to_submitted",
        test_type=TestType.POSITIVE_TRANSITION,
        entity="Order",
        description="Order transitions from draft to submitted on customer.submit",
        from_state="draft",
        to_state="submitted",
        trigger="customer.submit",
        guards=["line_items.count > 0", "line_items.all(li => li.product.in_stock)"],
        effects=["reserve_inventory(line_items)"],
    )


@pytest.fixture
def negative_transition_test():
    """A negative transition test case."""
    return TestCase(
        name="test_order_cannot_skip_draft_to_delivered",
        test_type=TestType.NEGATIVE_TRANSITION,
        entity="Order",
        description="Order cannot skip from draft directly to delivered",
        from_state="draft",
        to_state="delivered",
    )


@pytest.fixture
def happy_path_test():
    """A happy path test case."""
    return TestCase(
        name="test_order_lifecycle_to_delivered",
        test_type=TestType.HAPPY_PATH,
        entity="Order",
        description="Test path: draft → submitted → delivered",
        path=["draft", "submitted", "delivered"],
    )


@pytest.fixture
def invariant_test():
    """An invariant test case."""
    return TestCase(
        name="test_order_invariant_total_equals_sum",
        test_type=TestType.ENTITY_INVARIANT,
        entity="Order",
        description="Order total equals sum of line item subtotals",
        formal="total == line_items.sum(li => li.quantity * li.unit_price)",
    )


class TestFormatTestFile:
    """Tests for format_test_file."""

    def test_includes_file_docstring(self, positive_transition_test):
        """Output should include file docstring."""
        test_file = TestFile(
            entity="Order",
            filename="test_order.py",
            test_cases=[positive_transition_test],
        )

        output = format_test_file(test_file)

        assert '"""Generated tests for Order entity.' in output
        assert "Auto-generated by Lattice" in output

    def test_includes_pytest_import(self, positive_transition_test):
        """Output should import pytest."""
        test_file = TestFile(
            entity="Order",
            filename="test_order.py",
            test_cases=[positive_transition_test],
        )

        output = format_test_file(test_file)

        assert "import pytest" in output

    def test_generates_fixtures_for_states(self, positive_transition_test):
        """Should generate fixtures for states used in tests."""
        test_file = TestFile(
            entity="Order",
            filename="test_order.py",
            test_cases=[positive_transition_test],
        )

        output = format_test_file(test_file)

        assert "@pytest.fixture" in output
        assert "def order_in_draft_state():" in output

    def test_positive_transition_class(self, positive_transition_test):
        """Should create TestPositiveTransitions class."""
        test_file = TestFile(
            entity="Order",
            filename="test_order.py",
            test_cases=[positive_transition_test],
        )

        output = format_test_file(test_file)

        assert "class TestPositiveTransitions:" in output

    def test_includes_guards_in_docstring(self, positive_transition_test):
        """Guards should be included in test docstring."""
        test_file = TestFile(
            entity="Order",
            filename="test_order.py",
            test_cases=[positive_transition_test],
        )

        output = format_test_file(test_file)

        assert "Guards:" in output
        assert "line_items.count > 0" in output

    def test_includes_effects_in_docstring(self, positive_transition_test):
        """Effects should be included in test docstring."""
        test_file = TestFile(
            entity="Order",
            filename="test_order.py",
            test_cases=[positive_transition_test],
        )

        output = format_test_file(test_file)

        assert "Effects:" in output
        assert "reserve_inventory" in output

    def test_includes_trigger_comment(self, positive_transition_test):
        """Should include trigger as comment."""
        test_file = TestFile(
            entity="Order",
            filename="test_order.py",
            test_cases=[positive_transition_test],
        )

        output = format_test_file(test_file)

        assert "# Trigger: customer.submit" in output

    def test_negative_transition_class(self, negative_transition_test):
        """Should create TestNegativeTransitions class."""
        test_file = TestFile(
            entity="Order",
            filename="test_order.py",
            test_cases=[negative_transition_test],
        )

        output = format_test_file(test_file)

        assert "class TestNegativeTransitions:" in output

    def test_happy_path_class(self, happy_path_test):
        """Should create TestHappyPaths class."""
        test_file = TestFile(
            entity="Order",
            filename="test_order.py",
            test_cases=[happy_path_test],
        )

        output = format_test_file(test_file)

        assert "class TestHappyPaths:" in output
        assert "draft -> submitted -> delivered" in output

    def test_invariants_class(self, invariant_test):
        """Should create TestInvariants class."""
        test_file = TestFile(
            entity="Order",
            filename="test_order.py",
            test_cases=[invariant_test],
        )

        output = format_test_file(test_file)

        assert "class TestInvariants:" in output
        assert "Formal:" in output

    def test_valid_python_syntax(
        self,
        positive_transition_test,
        negative_transition_test,
        happy_path_test,
        invariant_test,
    ):
        """Generated code should be valid Python."""
        test_file = TestFile(
            entity="Order",
            filename="test_order.py",
            test_cases=[
                positive_transition_test,
                negative_transition_test,
                happy_path_test,
                invariant_test,
            ],
        )

        output = format_test_file(test_file)

        # This should not raise SyntaxError
        compile(output, "test_order.py", "exec")


class TestFormatSystemInvariantsFile:
    """Tests for format_system_invariants_file."""

    def test_includes_file_docstring(self):
        """Output should include file docstring."""
        test_cases = [
            TestCase(
                name="test_system_invariant_no_overselling",
                test_type=TestType.SYSTEM_INVARIANT,
                entity="system",
                description="No overselling allowed",
            )
        ]

        output = format_system_invariants_file(test_cases)

        assert '"""Generated tests for system invariants.' in output

    def test_creates_system_invariants_class(self):
        """Should create TestSystemInvariants class."""
        test_cases = [
            TestCase(
                name="test_system_invariant_no_overselling",
                test_type=TestType.SYSTEM_INVARIANT,
                entity="system",
                description="No overselling allowed",
            )
        ]

        output = format_system_invariants_file(test_cases)

        assert "class TestSystemInvariants:" in output

    def test_valid_python_syntax(self):
        """Generated code should be valid Python."""
        test_cases = [
            TestCase(
                name="test_system_invariant_no_overselling",
                test_type=TestType.SYSTEM_INVARIANT,
                entity="system",
                description="No overselling allowed",
                formal="available_inventory >= 0",
            ),
            TestCase(
                name="test_system_invariant_financial_consistency",
                test_type=TestType.SYSTEM_INVARIANT,
                entity="system",
                description="Financial consistency check",
            ),
        ]

        output = format_system_invariants_file(test_cases)

        # This should not raise SyntaxError
        compile(output, "test_system.py", "exec")
